# Generated by Django 5.0.3 on 2026-03-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
